# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apexlogs < Formula
  desc "A simple terminal UI for viewing Salesforce logs"
  homepage "https://github.com/cdelmoral/apexlogs"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Darwin_x86_64.tar.gz"
      sha256 "79134991d20e4f35255daa5aff4efc48428cf6465dcb899047540c8b2638e459"

      def install
        bin.install "apexlogs"
      end
    end
    on_arm do
      url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Darwin_arm64.tar.gz"
      sha256 "157d8c47841333a1d071878d264fdbbf1438098bf7fb23936ae1e6cf7bfc33cc"

      def install
        bin.install "apexlogs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Linux_x86_64.tar.gz"
        sha256 "ade19be605aa8ead654b109de9844be3628f4257481c93ed85b93cf4f17a1678"

        def install
          bin.install "apexlogs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Linux_arm64.tar.gz"
        sha256 "5b44345549a995753ecad5694a090cd11168285cff491f138d363c289c97bc81"

        def install
          bin.install "apexlogs"
        end
      end
    end
  end
end
