# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apexlogs < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Darwin_x86_64.tar.gz"
      sha256 "d1973ff9f0879cf3ed60fbd692c2f6e6101ad5104506b16696c5de390790be02"

      def install
        bin.install "apexlogs"
      end
    end
    on_arm do
      url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Darwin_arm64.tar.gz"
      sha256 "558248e320422bb7873cf477717f8f5a4f1153f935a5b5b7884aff6f60884182"

      def install
        bin.install "apexlogs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Linux_x86_64.tar.gz"
        sha256 "41de5fc5629ca83b9ee3c4bbb836305ad1b47ad48df6626910ef355966641de9"

        def install
          bin.install "apexlogs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Linux_arm64.tar.gz"
        sha256 "bddabdda787605f1062a9829ca33c0bdd07666d623d9658fbbcc9962b4373530"

        def install
          bin.install "apexlogs"
        end
      end
    end
  end
end
