# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Apexlogs < Formula
  desc "Simple terminal UI for viewing Salesforce logs"
  homepage "https://github.com/cdelmoral/apexlogs"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Darwin_x86_64.tar.gz"
      sha256 "4f70bbfb6ae281bfb7040b8d54d33cb74db724b795e262d7c5da8ba64a51d24a"

      def install
        bin.install "apexlogs"
      end
    end
    on_arm do
      url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Darwin_arm64.tar.gz"
      sha256 "85d05d32bdca4a5d6aea2a5659638e77f1ed7f5d5e6391d62325f04fea68e2a1"

      def install
        bin.install "apexlogs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Linux_x86_64.tar.gz"
        sha256 "ecafb6ac7f28317080e0eb37fcbd7cfe7835a7e45fbb5203a66633c4bb48de91"

        def install
          bin.install "apexlogs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cdelmoral/apexlogs/releases/download/v0.1.0/apexlogs_Linux_arm64.tar.gz"
        sha256 "5eb11be3533e8cf221ac43e0d74f450bbcca9c31819a34fe603d0dd00b17da5a"

        def install
          bin.install "apexlogs"
        end
      end
    end
  end
end
